# Generated by Django 3.2.2 on 2021-05-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runstatus",
            name="progress",
        ),
        migrations.CreateModel(
            name="RunProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("percent", models.FloatField()),
                ("snakemake_timestamp", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflow.run"
                    ),
                ),
            ],
        ),
    ]
