# Generated by Django 3.2.2 on 2021-05-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='version',
        ),
        migrations.AddField(
            model_name='workflowregistry',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='workflowregistry',
            unique_together={('name', 'version')},
        ),
    ]
