# Generated by Django 3.2.2 on 2021-05-17 15:51

from django.db import migrations, models
import workflow.models
import workflow.storage


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='result_is_private',
        ),
        migrations.AddField(
            model_name='run',
            name='run_is_private',
            field=models.BooleanField(default=False, help_text='Wether to show the run and it results publicly.'),
        ),
        migrations.AlterField(
            model_name='run',
            name='config',
            field=models.FileField(blank=True, help_text='Optional. Upload a changed config file here. Else the default config from the workflow is used.', max_length=200, storage=workflow.storage.OverwriteStorage(), upload_to=workflow.models.config_path),
        ),
        migrations.AlterField(
            model_name='run',
            name='cores',
            field=models.PositiveSmallIntegerField(default=6, help_text='Number of maximum CPU cores/jobs running in parallel.'),
        ),
        migrations.AlterField(
            model_name='run',
            name='sample_sheet',
            field=models.FileField(help_text='Required. Paths to input data files must start with "data/".', max_length=200, storage=workflow.storage.OverwriteStorage(), upload_to=workflow.models.sample_sheet_path),
        ),
        migrations.AlterField(
            model_name='run',
            name='target',
            field=models.CharField(default='all', help_text='Target(s) to build by snakemake. May be rules or files.', max_length=30),
        ),
    ]
