# Generated by Django 3.2.2 on 2021-05-17 18:35

from django.db import migrations, models
import workflow.models
import workflow.storage


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20210517_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_is_private',
            field=models.BooleanField(default=False, help_text='Whether to show the run and it results publicly.'),
        ),
        migrations.AlterField(
            model_name='run',
            name='sample_sheet',
            field=models.FileField(help_text='Required. Upload your sample sheet here. Paths to input data files must start with "data/".', max_length=200, storage=workflow.storage.OverwriteStorage(), upload_to=workflow.models.sample_sheet_path),
        ),
        migrations.AlterField(
            model_name='runinputfile',
            name='input_data',
            field=models.FileField(help_text='Required. The input data for your run.', max_length=200, storage=workflow.storage.OverwriteStorage(), upload_to=workflow.models.input_data_path),
        ),
    ]
