# Generated by Django 3.2.2 on 2021-05-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20210511_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='registration',
            new_name='parent_workflow',
        ),
    ]
