# Generated by Django 3.2.2 on 2021-05-11 19:51

from django.db import migrations, models
import django.db.models.deletion
import workflow.models
import workflow.storage


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_rename_registration_workflow_parent_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='input_data',
        ),
        migrations.AlterField(
            model_name='run',
            name='config',
            field=models.FileField(max_length=200, storage=workflow.storage.OverwriteStorage(), upload_to=workflow.models.config_path),
        ),
        migrations.AlterField(
            model_name='run',
            name='sample_sheet',
            field=models.FileField(max_length=200, storage=workflow.storage.OverwriteStorage(), upload_to=workflow.models.sample_sheet_path),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='path_config',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='path_sample_sheet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='path_snakefile',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.FileField(max_length=200, storage=workflow.storage.OverwriteStorage(), upload_to=workflow.models.input_data_path)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.run')),
            ],
        ),
    ]
